name: SecondChapter-Node.js CI

on:
  push:
    branches: [ "develop", "master", "release/sprint-*" ]
  pull_request:
    branches: [ "develop", "master", "release/sprint-*" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Run tests with coverage
        run: npm test > coverage.log

      - name: Read coverage log
        id: coverage
        run: |
          echo "text<<EOF" >> $GITHUB_OUTPUT
          cat coverage.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🧪 Code Coverage Report (Vitest)
            ```
            ${{ steps.coverage.outputs.text }}
            ```
